/**
 * ufcStatsTool.js
 *
 * Read-only access to the ufc_stats.db SQLite database generated by data_scrapper.
 * Provides detailed fight statistics (sig strikes, TDs, control time, per-round breakdowns)
 * sourced from ufcstats.com — data the Google Sheets history cache does not have.
 *
 * Configured via UFC_STATS_DB_PATH env var. Gracefully no-ops if the file is missing.
 */

import Database from 'better-sqlite3';
import path from 'node:path';
import os from 'node:os';

const TAG = '[ufcStatsTool]';

let db = null;

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

export function initUfcStatsTool({ dbPath } = {}) {
  const resolved =
    dbPath ||
    process.env.UFC_STATS_DB_PATH ||
    path.join(os.homedir(), '.ufc-orchestrator-bot', 'ufc_stats.db');

  try {
    db = new Database(resolved, { readonly: true, fileMustExist: true });
    console.log(`${TAG} Loaded ufc_stats.db from ${resolved}`);
  } catch (err) {
    db = null;
    console.warn(`${TAG} ufc_stats.db not found at ${resolved} — tool disabled. (${err.message})`);
  }
}

export function isAvailable() {
  return db !== null;
}

/**
 * getFreshnessMeta()
 *
 * Returns basic metadata about the loaded ufc_stats.db for freshness reporting.
 */
export function getFreshnessMeta() {
  if (!db) return null;
  try {
    const meta = db
      .prepare(
        `SELECT MAX(event_date) AS latest_fight_date,
                COUNT(*) AS fight_count
         FROM fights`
      )
      .get();
    const upcomingRow = db.prepare('SELECT COUNT(*) AS cnt FROM upcoming_fights').get();
    return {
      isAvailable: true,
      latestFightDate: meta?.latest_fight_date || null,
      fightCount: Number(meta?.fight_count) || 0,
      upcomingCount: Number(upcomingRow?.cnt) || 0,
      dbPath: db.name || null,
    };
  } catch {
    return { isAvailable: true, latestFightDate: null, fightCount: 0, upcomingCount: 0, dbPath: null };
  }
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * getFighterStats({ fighterName, limit, includeRounds })
 *
 * Returns last `limit` fights for a fighter with full totals and optional
 * per-round breakdowns. Uses a two-tier name matching strategy.
 *
 * @returns {{ fighter: string, fights: object[] } | { ok: false, error: string }}
 */
export function getFighterStats({ fighterName, limit = 8, includeRounds = false } = {}) {
  if (!db) {
    return {
      ok: false,
      error: 'ufc_stats.db no disponible. Configurá UFC_STATS_DB_PATH y ejecutá el scraper.',
    };
  }
  if (!fighterName || typeof fighterName !== 'string') {
    return { ok: false, error: 'Nombre de peleador requerido.' };
  }

  const name = fighterName.trim();
  const n = Math.min(Math.max(1, Number(limit) || 8), 20);

  const rows = _queryFights(name, n);
  if (rows.length === 0) {
    return { ok: false, error: `No se encontraron peleas para "${name}" en ufc_stats.db.` };
  }

  const fights = rows.map((row) => {
    const isF1 = _isF1(row, name);
    const prefix = isF1 ? 'f1' : 'f2';
    const result = isF1 ? row.fighter_1_result : row.fighter_2_result;
    const opponent = isF1 ? row.fighter_2_name : row.fighter_1_name;
    const resolvedName = isF1 ? row.fighter_1_name : row.fighter_2_name;

    const fight = {
      fight_id: row.fight_id,
      fighter: resolvedName,
      opponent,
      date: row.event_date,
      event: row.event_name,
      result,
      method: row.method,
      method_detail: row.method_detail || undefined,
      round: row.round,
      time: row.time,
      weight_class: row.weight_class,
      referee: row.referee || undefined,
      bonuses: _parseBonuses(row.bonuses),
      stats: _buildStats(row, prefix),
    };

    if (includeRounds) {
      fight.rounds = _queryRounds(row.fight_id, isF1 ? 1 : 2);
    }

    return fight;
  });

  const freshness = getFreshnessMeta();
  return {
    fighter: fights[0]?.fighter || name,
    fights,
    dataSource: 'ufc_stats_db',
    dbBuiltAt: freshness?.latestFightDate || null,
  };
}

// ---------------------------------------------------------------------------
// Private helpers
// ---------------------------------------------------------------------------

function _isF1(row, name) {
  const n = name.toLowerCase();
  return (
    row.fighter_1_name.toLowerCase() === n ||
    row.fighter_1_name.toLowerCase().includes(n)
  );
}

function _queryFights(name, limit) {
  // Tier 1: exact case-insensitive
  let rows = db
    .prepare(
      `SELECT * FROM fights
       WHERE LOWER(fighter_1_name) = LOWER(?) OR LOWER(fighter_2_name) = LOWER(?)
       ORDER BY event_date DESC LIMIT ?`
    )
    .all(name, name, limit);
  if (rows.length) return rows;

  // Tier 2: partial match — handles "Pereira" → "Alex Pereira"
  const like = `%${name}%`;
  return db
    .prepare(
      `SELECT * FROM fights
       WHERE fighter_1_name LIKE ? OR fighter_2_name LIKE ?
       ORDER BY event_date DESC LIMIT ?`
    )
    .all(like, like, limit);
}

function _queryRounds(fightId, fighterNum) {
  return db
    .prepare(
      `SELECT round, kd,
              sig_str_landed, sig_str_att, sig_str_pct,
              total_str_landed, total_str_att,
              td_landed, td_att, td_pct,
              sub_att, rev, ctrl,
              head_landed, head_att,
              body_landed, body_att,
              leg_landed, leg_att,
              distance_landed, distance_att,
              clinch_landed, clinch_att,
              ground_landed, ground_att
       FROM fight_rounds
       WHERE fight_id = ? AND fighter = ?
       ORDER BY round ASC`
    )
    .all(fightId, fighterNum);
}

function _buildStats(row, prefix) {
  return {
    kd:               row[`${prefix}_kd`],
    sig_str_landed:   row[`${prefix}_sig_str_landed`],
    sig_str_att:      row[`${prefix}_sig_str_att`],
    sig_str_pct:      row[`${prefix}_sig_str_pct`],
    total_str_landed: row[`${prefix}_total_str_landed`],
    total_str_att:    row[`${prefix}_total_str_att`],
    td_landed:        row[`${prefix}_td_landed`],
    td_att:           row[`${prefix}_td_att`],
    td_pct:           row[`${prefix}_td_pct`],
    sub_att:          row[`${prefix}_sub_att`],
    rev:              row[`${prefix}_rev`],
    ctrl:             row[`${prefix}_ctrl`],
    head_landed:      row[`${prefix}_head_landed`],
    head_att:         row[`${prefix}_head_att`],
    body_landed:      row[`${prefix}_body_landed`],
    body_att:         row[`${prefix}_body_att`],
    leg_landed:       row[`${prefix}_leg_landed`],
    leg_att:          row[`${prefix}_leg_att`],
    distance_landed:  row[`${prefix}_distance_landed`],
    distance_att:     row[`${prefix}_distance_att`],
    clinch_landed:    row[`${prefix}_clinch_landed`],
    clinch_att:       row[`${prefix}_clinch_att`],
    ground_landed:    row[`${prefix}_ground_landed`],
    ground_att:       row[`${prefix}_ground_att`],
  };
}

function _parseBonuses(raw) {
  try { return JSON.parse(raw); } catch { return []; }
}

// ---------------------------------------------------------------------------
// Upcoming fights
// ---------------------------------------------------------------------------

/**
 * getUpcomingFights({ eventName, limit })
 *
 * Returns scheduled (not yet fought) fights from the upcoming_fights table.
 * Optionally filter by event name substring.
 *
 * @returns {{ fights: object[] } | { ok: false, error: string }}
 */
export function getUpcomingFights({ eventName, limit = 50 } = {}) {
  if (!db) {
    return {
      ok: false,
      error: 'ufc_stats.db no disponible. Configurá UFC_STATS_DB_PATH y ejecutá el scraper.',
    };
  }

  const n = Math.min(Math.max(1, Number(limit) || 50), 200);

  let rows;
  if (eventName && typeof eventName === 'string' && eventName.trim()) {
    const like = `%${eventName.trim()}%`;
    rows = db
      .prepare(
        `SELECT * FROM upcoming_fights
         WHERE event_name LIKE ?
         ORDER BY event_date ASC, card_order ASC
         LIMIT ?`
      )
      .all(like, n);
  } else {
    rows = db
      .prepare(
        `SELECT * FROM upcoming_fights
         ORDER BY event_date ASC, card_order ASC
         LIMIT ?`
      )
      .all(n);
  }

  if (rows.length === 0) {
    return { ok: false, error: 'No se encontraron peleas programadas en upcoming_fights.' };
  }

  return { fights: rows };
}

// ---------------------------------------------------------------------------
// Fight history rows — 2D format for autoSettlement compatibility
// ---------------------------------------------------------------------------

/**
 * getFightHistoryRows({ fighterA, fighterB, limit })
 *
 * Returns completed fights as 2D rows in the format expected by resolveAutoSettlementCandidate:
 *   [date, event, fighterA, fighterB, division, winner, method, round, time]  (indices 0-8)
 *
 * - Without fighter args: returns all completed fights (limit 5000) for settlement scanning.
 * - With fighterA/fighterB: applies two-tier name matching (exact → partial).
 *
 * @returns {Array<Array<any>>} Empty array if db not available.
 */
export function getFightHistoryRows({ fighterA, fighterB, limit = 5000 } = {}) {
  if (!db) return [];

  const n = Math.min(Math.max(1, Number(limit) || 5000), 10000);

  let rows;
  if (fighterA || fighterB) {
    const name = (fighterA || fighterB).trim();
    rows = _queryFights(name, n);
  } else {
    // All completed fights — fighter_1_result must be non-empty (fight has happened)
    rows = db
      .prepare(
        `SELECT fight_id, event_date, event_name, fighter_1_name, fighter_2_name,
                weight_class, fighter_1_result, fighter_2_result, method, round, time
         FROM fights
         WHERE fighter_1_result IS NOT NULL AND fighter_1_result != ''
         ORDER BY event_date DESC
         LIMIT ?`
      )
      .all(n);
  }

  return rows.map((row) => {
    const winner =
      row.fighter_1_result === 'W'
        ? row.fighter_1_name
        : row.fighter_2_result === 'W'
          ? row.fighter_2_name
          : '';
    return [
      row.event_date,       // [0] date
      row.event_name,       // [1] event
      row.fighter_1_name,   // [2] fighterA
      row.fighter_2_name,   // [3] fighterB
      row.weight_class,     // [4] division
      winner,               // [5] winner
      row.method,           // [6] method
      row.round,            // [7] round
      row.time,             // [8] time
    ];
  });
}
